#!/usr/bin/env bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

"$script_dir"/common/install-hakari.sh

set -x
cargo hakari generate
cargo hakari manage-deps
