#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Install cargo-binstall if necessary
if ! cargo --list | grep -q binstall; then
    # The workspace toolchain is using rust 1.77.0, so we need to install a version of
    # cargo-binstall that is compatible with that.
    cargo install cargo-binstall --version "<1.7.0"
fi

# Install cargo-nextest using cargo binstall if necessary
if ! cargo --list | grep -q nextest; then
    cargo binstall cargo-nextest --no-confirm
fi

# Run workspace tests
set -x
cargo nextest run "$@"
