chain_id = 1337
epoch_start = 1684276288383
epoch_time = 120000
epochs_per_year = 365
committee_size = 10
node_count = 100
min_stake = 1000
eligibility_time = 1
lock_time = 5
protocol_share = 0
node_share = 80
service_builder_share = 20
max_inflation = 10
consumer_rebate = 0
max_boost = 4
max_lock_time = 1460                                                 # 1460 days(epoch) meaning 4 years
supply_at_genesis = 1000000                                          # set to 1 million for testing, to be determined when initial allocations are set
min_num_measurements = 2
protocol_fund_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
governance_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
reputation_ping_timeout = "15s"
topology_target_k = 8
topology_min_nodes = 16
committee_selection_beacon_commit_phase_duration = 10
committee_selection_beacon_reveal_phase_duration = 10

[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "F5tV4PLSzx1Lt4mYBe13aYQ8hsLMTCfjgY2pLr82AumH"
consensus_public_key = "u76G7q22Qc5nRC5Fi6dzbNE7FQxqRKEtTS9qjDftWFwhBKmoozGLv8wFiFmGnYDFMEKyYxozWRdM3wgjs1Na3fvxDARxi9CSNJUZJfPXC2WUu3uLnUw96jPBRp7rtHEzS5H"
worker_public_key = "F5tV4PLSzx1Lt4mYBe13aYQ8hsLMTCfjgY2pLr82AumH"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
ports.primary = 14310
ports.worker = 14311
ports.mempool = 14210
ports.rpc = 14230
ports.pool = 14300
ports.pinger = 14350
ports.handshake.http = 14220
ports.handshake.webrtc = 14320
ports.handshake.webtransport = 14321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "Qt1DzUoTEn7n4itYpAPhaDsXhcriuXe1e7n7uZztGfg"
consensus_public_key = "21cq5icj1pWKk9DBwdUFSW6nqBrwtzHtvKWcLNrqFRxZV8UbdKYzdoSs8C1u7s7M4FKADDqsHnxETh56hdSK2Z65nsbW3xME1fNcT1s8dfHwCFk567mV4fmSSgH73mTe1H3a"
worker_public_key = "Qt1DzUoTEn7n4itYpAPhaDsXhcriuXe1e7n7uZztGfg"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
ports.primary = 24310
ports.worker = 24311
ports.mempool = 24210
ports.rpc = 24230
ports.pool = 24300
ports.pinger = 24350
ports.handshake.http = 24220
ports.handshake.webrtc = 24320
ports.handshake.webtransport = 24321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "8XT8Kb1PCd2kzmwHLQ8Nw9aAuKJin6tihaPQBCyf6ymn"
consensus_public_key = "uNHES9wjYK3HkbcPWrBiQQZ2NmcfBVKke8tbH9X7RFT9ZvjL5f55FfPvpjh2RWpxTRyMhKAxYG42TaRv2RGyEZkYcx2aJMfgPYqYaiT8KC1EPHzJYgVmYc7z2ER69LNWC7r"
worker_public_key = "8XT8Kb1PCd2kzmwHLQ8Nw9aAuKJin6tihaPQBCyf6ymn"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
ports.primary = 34310
ports.worker = 34311
ports.mempool = 34210
ports.rpc = 34230
ports.pool = 34300
ports.pinger = 34350
ports.handshake.http = 34220
ports.handshake.webrtc = 34320
ports.handshake.webtransport = 34321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x959807B8D94B324A74117956731F09E2893aCd72"
primary_public_key = "DA3mDUC5y7s5dNF4bL5MfTy7TtXjwt16rtspGuJcwZHS"
consensus_public_key = "rnSokyL9vj1cnxsrHVmuMCP677Ns4Xh6N5FmfKvjinxVCA9W8w6DiqXSQTX92TtoapS5eqcHCuKnNKamqxh5MnLpHGZ9UkjKUPWsc7hnQXqQobHTXdw1GSh88wEir94mEba"
worker_public_key = "DA3mDUC5y7s5dNF4bL5MfTy7TtXjwt16rtspGuJcwZHS"
primary_domain = "127.0.0.1"
worker_domain = "127.0.0.1"
ports.primary = 44310
ports.worker = 44311
ports.mempool = 44210
ports.rpc = 44230
ports.pool = 44300
ports.pinger = 44350
ports.handshake.http = 44220
ports.handshake.webrtc = 44320
ports.handshake.webtransport = 44321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[service]]
id = 0
owner = "0xDC0A31F9eeb151f82BF1eE6831095284fC215Ee7"
commodity_type = "Bandwidth"

[[service]]
id = 1
owner = "0x684166BDbf530a256d7c92Fa0a4128669aFd9B9F"
commodity_type = "Compute"

[[account]]
public_key = "0x959807B8D94B324A74117956731F09E2893aCd72"
flk_balance = "100690000000000000000"
stables_balance = 100
bandwidth_balance = 100

[[commodity_prices]]
commodity = "Bandwidth"
price = 0.1

[[commodity_prices]]
commodity = "Compute"
price = 0.2

[rep_scores]

[total_served]

[current_epoch_served]

[client]
