[package]
name = "lightning-watcher"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
fleek-crypto.workspace = true
futures.workspace = true
tokio.workspace = true
tracing.workspace = true
lightning-interfaces = { path = "../interfaces" }
lightning-types = { path = "../types" }
lightning-utils = { path = "../../core/utils" }
lightning-workspace-hack.workspace = true
