[package]
name = "deno_fleek"
version = "0.0.1"
edition.workspace = true

[dependencies]
anyhow.workspace = true
arrayref = "0.3"
b3fs = { path = "../../../lib/b3fs" }
cid = "0.11"
fn-sdk = { path = "../../../lib/sdk" }
fleek-crypto.workspace = true
lightning-schema = { path = "../../../core/schema" }
lightning-workspace-hack.workspace = true
tracing = "0.1"
serde.workspace = true
serde_json.workspace = true

# Deno core + webapi extensions
deno_ast = { version = "0.42", features = ["transpiling"] }
deno_core = "0.314.2"
deno_fs = "0.83.0"
deno_io = "0.83.0"
deno_media_type = "0.1"
deno_net = "0.165.0"
deno_node = "0.110.0"
deno_permissions = "0.33.0"
deno_web = "0.204.0"
deno_fetch = "0.197.0"
deno_websocket = "0.178.0"
