[package]
name = "fleek-service-sgx-enclave"
version = "0.1.0"
edition = "2021"

[dependencies]
# Project libs (release only)
blake3-tree = "=0.1.0"

# Error stuffs
anyhow = "=1.0.86"
thiserror = "=1.0.63"

# IO
arrayref = "=0.3.8"
bytes = "=1.7.1"


# Encodings
hex = "=0.4.3"
bs58 = "=0.5.1"
serde = { version = "=1.0.209", features = ["derive"] }
serde_json = "=1.0.127"

# Networking
# rouille = "=3.6.2"
rouille = {git = "https://github.com/mithril-security/rouille-sgx.git", rev = "ff83153bb5870efdcf6401511f844713af6828db"}

# WASM Runtime
wasmi = "=0.36.0"

# SGX Utilities
sgx-isa = {version = "0.4.0", features = ["serde"] }

[dependencies.fleek-remote-attestation]
# Notes about cryptography dependencies:
#   - p256: pure rust, from rustcrypto
#   - x509-verify: pure rust, uses rustcrypto deps
git = "https://github.com/fleek-network/fleek-remote-attestation"
rev = "6414a1a9e730d74bd30402c2351e8a193f8154a0"

[dependencies.ecies]
# Notes about cryptography dependencies:
#   - `aes-gcm`: pure rust, has been audited
#   - `libsecp256k1`: pure rust, from paritytech
version = "=0.2.7"
default-features = false
features = ["pure", "std"]

[dependencies.libsecp256k1]
version = "0.7.1"
