[package]
name = "fleek-service-sgx-enclave"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3-tree = { path = "../../../lib/blake3-tree" }

anyhow.workspace = true
bytes.workspace = true
arrayref = "0.3"
hex = "0.4"
