[package]
name = "fleek-service-sgx-enclave"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3-tree = { path = "../../../lib/blake3-tree" }

anyhow = "=1.0"
bytes = "=1.7"
serde = { version = "=1.0", features = [ "derive" ] }
serde_json = "=1.0"
arrayref = "=0.3"
hex = "=0.4"

wasmi = "=0.36.0"
