chain_id = 59330
epoch_start = 1710261708786
epoch_time = 1800000
committee_size = 6
min_stake = 1000
eligibility_time = 1
lock_time = 5
protocol_share = 0
node_share = 80
service_builder_share = 20
max_inflation = 10
consumer_rebate = 0
max_boost = 4
max_lock_time = 1460                                                 # 1460 days(epoch) meaning 4 years
supply_at_genesis = 1000000                                          # set to 1 million for testing, to be determined when initial allocations are set
protocol_fund_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
governance_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "AuKT4zYJJ5zQ5eBiZ5peUAn2HXR8HdPaQufrc4xR3ikh"
consensus_public_key = "rZ2PghFsADqPdzgHsbqVbNQGuSqQYM2HnEPQBZk2QGghqTJczHhFnW4n4FEDo91ijBR597ixttWTVLNcwUW1af7fDr7siRFb4pTR86eA4S6qz8xC9XPW3ZXWfkDZL2uRM3q"
worker_public_key = "AuKT4zYJJ5zQ5eBiZ5peUAn2HXR8HdPaQufrc4xR3ikh"
primary_domain = "15.204.100.217"
worker_domain = "15.204.100.217"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "DpKMJvksUr4C49xBrTceHRwoVnn2kb7pMJVEcTVTGTSg"
consensus_public_key = "ztVb9bJ3oKs389EG4zY3CsiSUKD2kuNYhtAYpfSC6fAhEcaFUvL4xDY5RCMLWWT2BVZN4QHPSsaSLgrwKi7WsWhnGEeGdXu4pyADP3bDq4VN3aUwa9PcM8o2eVugbkgJDca"
worker_public_key = "DpKMJvksUr4C49xBrTceHRwoVnn2kb7pMJVEcTVTGTSg"
primary_domain = "15.204.222.17"
worker_domain = "15.204.222.17"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "GHGHDb8gfJ2Y3BR8yPvKRvQzg8hwWgZSafBMyM6e3MVF"
consensus_public_key = "scia1Xa5joQR9HSY95HZFiNmtSPyuNfNLKGZsNDLqQrWxBT2UdXUMka5ja2QQesyySi5MSkhLGzCmxEeAUz4p1Wxobq3AESwhpb8kAv3PEMiJNoa35KtqBAWJVsRJfGzfsh"
worker_public_key = "GHGHDb8gfJ2Y3BR8yPvKRvQzg8hwWgZSafBMyM6e3MVF"
primary_domain = "141.95.99.62"
worker_domain = "141.95.99.62"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "AR23ttLTBvmR1hXzAmb2Q9JE41vBGgsgdk4TzkxDRVzk"
consensus_public_key = "ss3EbnJxPauz7BRw365cZPPcfSzYAdgp7qNx83ZcHr3yq4N8kgbhGsVGonNCuUfejSbt6unTxXhtJ9H8Bczw7vZuZc7gNWiQTFutprHsjSPRk99DLPB1CttwMB7VqyMeYw4"
worker_public_key = "AR23ttLTBvmR1hXzAmb2Q9JE41vBGgsgdk4TzkxDRVzk"
primary_domain = "57.128.101.225"
worker_domain = "57.128.101.225"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "JAbgKmAArVThcoUqDx9c382uforNVoN3H88cvJ3a5bC5"
consensus_public_key = "y4wGTXXczWSDPDCTQ4h45XNZwQQzWXr4MQrcnhmaupAUMURkFRP9vZQ3fAY1xY2F1jZgWkpqAcJxpNfcwotxfbVn56NBhuhABTzBapKLo7pRFd1ou5PBt4LpPZ4sWRnhiSA"
worker_public_key = "JAbgKmAArVThcoUqDx9c382uforNVoN3H88cvJ3a5bC5"
primary_domain = "148.113.16.127"
worker_domain = "148.113.16.127"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true


[[service]]
id = 0
owner = "0xDC0A31F9eeb151f82BF1eE6831095284fC215Ee7"
commodity_type = "Bandwidth"

[[service]]
id = 1
owner = "0x684166BDbf530a256d7c92Fa0a4128669aFd9B9F"
commodity_type = "Compute"

[[account]]
public_key = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
flk_balance = "100690000000000000000"
stables_balance = 100
bandwidth_balance = 100

[[commodity_prices]]
commodity = "Bandwidth"
price = 0.1

[[commodity_prices]]
commodity = "Compute"
price = 1

[rep_scores]

[total_served]

[current_epoch_served]

[client]
